### ISSUE TITLE
Can you compress the data and upload it to google drive? 

### ISSUE THREAD

**Issue by hykai209** [KellyYutongHe/satellite-pixel-synthesis-pytorch#2]
Can you compress the data and upload it to google drive? Your latest readme says that the data set is still under construction(I have downloaded the old dataset... :( ). Can you upload it in time when it is completed( : ) )? thanks!!!!

**Comment by KellyYutongHe** [comment]
Yeah of course. We just found out that there was some upload errors last time so we are uploading the data again. However, since we are experiencing power outage at Stanford recently, it take longer for this to complete. I’ll update the repo with the new links when it’s finished. Sorry about this.

**Comment by Depanshu-Sani** [comment]
FMoW Dataset is under construction as per the readme file, and a URL to the Texas Housing Dataset is provided. Is the URL correctly updated because I still can't find the compressed version of it?

**Comment by KellyYutongHe** [comment]
The Texas dataset should be updated and if you directly download the entire dataset from google drive it should be compressed for you. We plan to release a more comprehensive version of the fmow-sentinel dataset with our new paper so stay tuned for that!

**Comment by Depanshu-Sani** [comment]
Thanks for the quick response! 
I've been trying to download the google folder directly, but because the number of files in the subdirectories is huge, it fails to compress the folder every time. I also tried the following `gdrive` command that recursively copies the files onto the local machine using CLI:
`gdrive download 1rFjxWxpH_4SCa30y58e3OJnH0uIyiMuD --recursive`
But this is also taking a lot of time. Only ~40K images have been downloaded in two days. It would be great if you could provide a compressed file.

**Comment by KellyYutongHe** [comment]
Oh I see. Yeah it took a very long time for me to upload the images as well :). Alright I’ll upload a compressed version next week. Thank you for your patience!

**Comment by hykai209** [comment]
Rclone can help you to download this dataset by setting the transfers

> Thanks for the quick response! I've been trying to download the google folder directly, but because the number of files in the subdirectories is huge, it fails to compress the folder every time. I also tried the following `gdrive` command that recursively copies the files onto the local machine using CLI: `gdrive download 1rFjxWxpH_4SCa30y58e3OJnH0uIyiMuD --recursive` But this is also taking a lot of time. Only ~40K images have been downloaded in two days. It would be great if you could provide a compressed file.

**Comment by Depanshu-Sani** [comment]
Even using rclone took me weeks to download the dataset. Here is the [link](https://drive.google.com/file/d/17W4FCaatk7rV4Hn9F0vJSLncS0strSnL/) to the compressed dataset, if anyone else needs it.

**Comment by kanak8278** [comment]
@Depanshu-Sani, The link for the compressed data is not working. Can you share it again?
